In [1]:
import numpy as np
import re

In [2]:
data_string = '''age                          0.021***          
                              (0.004)          
                                               
IQ                           0.008***          
                              (0.001)          
                                               
south                        -0.099***         
                              (0.027)          
                                               
married                      0.201***          
                              (0.040)          
                                               
urban                        0.175***          
                              (0.028)          
                                               
Constant                     4.974***          
                              (0.165)'''
data_string

'age                          0.021***          \n                              (0.004)          \n                                               \nIQ                           0.008***          \n                              (0.001)          \n                                               \nsouth                        -0.099***         \n                              (0.027)          \n                                               \nmarried                      0.201***          \n                              (0.040)          \n                                               \nurban                        0.175***          \n                              (0.028)          \n                                               \nConstant                     4.974***          \n                              (0.165)'

In [3]:
data_num = re.findall(r'([-+]?\d+.\d+)',data_string)
data_num

['0.021',
 '0.004',
 '0.008',
 '0.001',
 '-0.099',
 '0.027',
 '0.201',
 '0.040',
 '0.175',
 '0.028',
 '4.974',
 '0.165']

In [4]:
# Выделим числа из строки с помощью регулярных выражений
#(необходимо выделить подстроку, удовлетворяющая определенному шаблону символов)
digital_date = re.findall(r'([-+]?\d+.\d+)',data_string)
digital_date

['0.021',
 '0.004',
 '0.008',
 '0.001',
 '-0.099',
 '0.027',
 '0.201',
 '0.040',
 '0.175',
 '0.028',
 '4.974',
 '0.165']

In [5]:
# Из одномерного списка сделаем двумерный список типа размерности (8,2)
# 8 --- количество коэффицентов, включая константу
# 2 --- потому что строка содержит оценку коэффицента и его ошибку
# так как исходны список содержит оценки коэффицентов и их ошибки
beta = np.reshape(digital_date,(6,2))
beta

array([['0.021', '0.004'],
       ['0.008', '0.001'],
       ['-0.099', '0.027'],
       ['0.201', '0.040'],
       ['0.175', '0.028'],
       ['4.974', '0.165']], dtype='<U6')

In [6]:

# ppl_string --- переменная, которая содержит изначальную строку данных
ppl_string = '''age IQ  south married urban
1 36  105   1      1      1  
2 29  123   0      1      0  
3 25  112   1      0      1 '''

In [9]:
ppl_lst = re.findall(r'([-+]?\d+)', ppl_string)
ppl_lst

['1',
 '36',
 '105',
 '1',
 '1',
 '1',
 '2',
 '29',
 '123',
 '0',
 '1',
 '0',
 '3',
 '25',
 '112',
 '1',
 '0',
 '1']

In [10]:
ppl_numb = np.reshape(ppl_lst,(3,6))
ppl_numb

array([['1', '36', '105', '1', '1', '1'],
       ['2', '29', '123', '0', '1', '0'],
       ['3', '25', '112', '1', '0', '1']], dtype='<U3')

In [11]:
ppl_numb = np.delete(ppl_numb,0,1)
ppl_numb

array([['36', '105', '1', '1', '1'],
       ['29', '123', '0', '1', '0'],
       ['25', '112', '1', '0', '1']], dtype='<U3')

In [12]:

ppl_numb = np.c_[ppl_numb,np.ones(3)]
ppl_numb

array([['36', '105', '1', '1', '1', '1.0'],
       ['29', '123', '0', '1', '0', '1.0'],
       ['25', '112', '1', '0', '1', '1.0']], dtype='<U32')

In [13]:

beta = beta.astype(float)
ppl_numb = ppl_numb.astype(float)

In [14]:
beta

array([[ 2.100e-02,  4.000e-03],
       [ 8.000e-03,  1.000e-03],
       [-9.900e-02,  2.700e-02],
       [ 2.010e-01,  4.000e-02],
       [ 1.750e-01,  2.800e-02],
       [ 4.974e+00,  1.650e-01]])

In [15]:

ppl_numb

array([[ 36., 105.,   1.,   1.,   1.,   1.],
       [ 29., 123.,   0.,   1.,   0.,   1.],
       [ 25., 112.,   1.,   0.,   1.,   1.]])

In [16]:

ppl_numb@beta[:,0]

array([6.847, 6.768, 6.471])