In [1]:
import numpy as np
import re

In [2]:
data_string = '''exper                        0.037***          
                              (0.006)          
                                               
I(exper2)                    -0.001***         
                             (0.0001)          
                                               
female                       -0.363***         
                              (0.040)          
                                               
married                      0.144***          
                              (0.045)          
                                               
smsa                         0.273***          
                              (0.044)          
                                               
Constant                     1.250***          
                              (0.061)'''
data_string

'exper                        0.037***          \n                              (0.006)          \n                                               \nI(exper2)                    -0.001***         \n                             (0.0001)          \n                                               \nfemale                       -0.363***         \n                              (0.040)          \n                                               \nmarried                      0.144***          \n                              (0.045)          \n                                               \nsmsa                         0.273***          \n                              (0.044)          \n                                               \nConstant                     1.250***          \n                              (0.061)'

In [3]:
# Выделим числа из строки с помощью регулярных выражений
#(необходимо выделить подстроку, удовлетворяющая определенному шаблону символов)
digital_date = re.findall(r'([-+]?\d+.\d+)',data_string)
digital_date

['0.037',
 '0.006',
 '-0.001',
 '0.0001',
 '-0.363',
 '0.040',
 '0.144',
 '0.045',
 '0.273',
 '0.044',
 '1.250',
 '0.061']

In [5]:
# Из одномерного списка сделаем двумерный список типа размерности (8,2)
# 8 --- количество коэффицентов, включая константу
# 2 --- потому что строка содержит оценку коэффицента и его ошибку
# так как исходны список содержит оценки коэффицентов и их ошибки
beta = np.reshape(digital_date,(6,2))
beta

array([['0.037', '0.006'],
       ['-0.001', '0.0001'],
       ['-0.363', '0.040'],
       ['0.144', '0.045'],
       ['0.273', '0.044'],
       ['1.250', '0.061']], dtype='<U6')

In [8]:
# ppl_string --- переменная, которая содержит изначальную строку данных
ppl_string = '''exper female married smsa
---------------------------
1   5     1       1     1  
2  26     0       0     1  
3  38     1       1     0'''


In [9]:
ppl_lst = re.findall(r'([-+]?\d+)', ppl_string)
ppl_lst

['1', '5', '1', '1', '1', '2', '26', '0', '0', '1', '3', '38', '1', '1', '0']

In [11]:
ppl_numb = np.reshape(ppl_lst,(3,5))
ppl_numb

array([['1', '5', '1', '1', '1'],
       ['2', '26', '0', '0', '1'],
       ['3', '38', '1', '1', '0']], dtype='<U2')

In [12]:
ppl_numb = np.delete(ppl_numb,0,1)
ppl_numb

array([['5', '1', '1', '1'],
       ['26', '0', '0', '1'],
       ['38', '1', '1', '0']], dtype='<U2')

In [13]:
ppl_numb = np.c_[ppl_numb,np.ones(3)]
ppl_numb

array([['5', '1', '1', '1', '1.0'],
       ['26', '0', '0', '1', '1.0'],
       ['38', '1', '1', '0', '1.0']], dtype='<U32')

In [17]:
ppl_numb = np.c_[ppl_numb,np.ones(3)]
ppl_numb

array([[ 5.,  1.,  1.,  1.,  1.,  1.],
       [26.,  0.,  0.,  1.,  1.,  1.],
       [38.,  1.,  1.,  0.,  1.,  1.]])

In [18]:
beta = beta.astype(float)
ppl_numb = ppl_numb.astype(float)

In [19]:
beta

array([[ 3.70e-02,  6.00e-03],
       [-1.00e-03,  1.00e-04],
       [-3.63e-01,  4.00e-02],
       [ 1.44e-01,  4.50e-02],
       [ 2.73e-01,  4.40e-02],
       [ 1.25e+00,  6.10e-02]])

In [20]:
ppl_numb

array([[ 5.,  1.,  1.,  1.,  1.,  1.],
       [26.,  0.,  0.,  1.,  1.,  1.],
       [38.,  1.,  1.,  0.,  1.,  1.]])

In [21]:

ppl_numb@beta[:,0]

array([1.488, 2.629, 2.565])