In [1]:
import numpy as np
import re

In [2]:
data_string = '''log(capital)                 0.208***          
                              (0.017)          
                                               
log(labour)                  0.715***          
                              (0.023)          
                                               
Constant                     -1.711***         
                              (0.097)'''
data_string

'log(capital)                 0.208***          \n                              (0.017)          \n                                               \nlog(labour)                  0.715***          \n                              (0.023)          \n                                               \nConstant                     -1.711***         \n                              (0.097)'

In [3]:
# Выделим числа из строки с помощью регулярных выражений
#(необходимо выделить подстроку, удовлетворяющая определенному шаблону символов)
digital_date = re.findall(r'([-+]?\d+.\d+)',data_string)
digital_date

['0.208', '0.017', '0.715', '0.023', '-1.711', '0.097']

In [4]:
# Из одномерного списка сделаем двумерный список типа размерности (8,2)
# 8 --- количество коэффицентов, включая константу
# 2 --- потому что строка содержит оценку коэффицента и его ошибку
# так как исходны список содержит оценки коэффицентов и их ошибки
beta = np.reshape(digital_date,(3,2))
beta

array([['0.208', '0.017'],
       ['0.715', '0.023'],
       ['-1.711', '0.097']], dtype='<U6')

In [5]:
beta[:,0]

array(['0.208', '0.715', '-1.711'], dtype='<U6')

In [6]:
# ppl_string --- переменная, которая содержит изначальную строку данных
ppl_string = '''capital labour
----------------
1  2.970    85  
2 10.450    60  
3  3.850   105'''

In [7]:
# Создадим список из чисел, содержащихся в строке. 
# ppl_list -- список, который будет состоять из подстрок, каждая из которых удовлетворяет определенному шаблону символов
ppl_lst = re.findall(r'([-+]?\d+.\d+|[-+]?\d+)',ppl_string)

In [8]:
ppl_numb = np.reshape(ppl_lst,(3,3))
ppl_numb

array([['1', '2.970', '85'],
       ['2 10', '450', '60'],
       ['3', '3.850', '105']], dtype='<U5')

In [9]:
# Необходимо удалить первый столбец, так как это нумерация строк
ppl_numb = np.delete(ppl_numb,0,1)
ppl_numb

array([['2.970', '85'],
       ['450', '60'],
       ['3.850', '105']], dtype='<U5')

In [14]:
ppl_numb = np.c_[ppl_numb,np.ones(3)]
ppl_numb

array([[  2.97,  85.  ,   1.  ],
       [450.  ,  60.  ,   1.  ],
       [  3.85, 105.  ,   1.  ]])

In [15]:
beta = beta.astype(float)
ppl_numb = ppl_numb.astype(float)

In [16]:
beta

array([[ 0.208,  0.017],
       [ 0.715,  0.023],
       [-1.711,  0.097]])

In [17]:
ppl_numb

array([[  2.97,  85.  ,   1.  ],
       [450.  ,  60.  ,   1.  ],
       [  3.85, 105.  ,   1.  ]])

In [18]:
ppl_numb@beta[:,0]

array([ 59.68176, 134.789  ,  74.1648 ])